"use client";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
type Row=Record<string,unknown>;
type Data={student:Row;sessions:Row[];fees:Row[];attendance:Row[];results:Row[];leaves:Row[];hostel:Row[];gate:Row[];notices:Row[]};
const money=(n:unknown)=>Number(n||0).toLocaleString("ur-PK");
const date=(v:unknown)=>v?new Date(String(v)).toLocaleDateString("ur-PK"):"—";
export default function PortalDashboard(){const router=useRouter(),[data,setData]=useState<Data|null>(null),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/portal/dashboard").then(async r=>{if(r.status===401){router.replace("/portal/login");return}const d=await r.json();d.success?setData(d):setError(d.message)}).catch(()=>setError("ریکارڈ حاصل نہیں ہوسکا۔"))},[router]);
 const stats=useMemo(()=>{if(!data)return null;const due=data.fees.reduce((s,x)=>s+Number(x.amount_due||0),0),paid=data.fees.reduce((s,x)=>s+Number(x.amount_paid||0),0);const present=data.attendance.filter(x=>x.attendance_status==="حاضر").length;return {due,paid,balance:due-paid,present,total:data.attendance.length}},[data]);
 async function logout(){await fetch("/api/portal/logout",{method:"POST"});router.replace("/portal/login")}
 if(error)return <div className="p-8 text-center text-red-700">{error}</div>;if(!data||!stats)return <div className="p-8 text-center">ریکارڈ لوڈ ہو رہا ہے…</div>;
 const s=data.student;return <main className="min-h-screen bg-slate-100 pb-12" dir="rtl"><header className="bg-blue-950 text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div><h1 className="text-2xl font-black">جامعہ بلال اسلامیہ</h1><p className="text-blue-200">والدین و طالب علم پورٹل</p></div><button onClick={logout} className="rounded-xl bg-white/10 px-4 py-2">لاگ آؤٹ</button></div></header><div className="mx-auto max-w-7xl space-y-7 px-5 py-7">
  <section className="rounded-3xl bg-white p-6 shadow"><div className="flex flex-wrap items-center gap-5"><div className="flex h-20 w-20 items-center justify-center rounded-full bg-blue-100 text-3xl">🎓</div><div><h2 className="text-3xl font-black text-slate-900">{String(s.student_name||"")}</h2><p className="mt-1 text-slate-600">والد: {String(s.father_name||"—")} • طالب علم نمبر: <span dir="ltr">{String(s.student_number||"")}</span></p><p className="text-slate-600">شعبہ: {String(s.current_department||"—")}</p></div></div></section>
  <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Card title="حاضری" value={`${stats.present}/${stats.total}`} note="حالیہ ریکارڈ" color="blue"/><Card title="کل واجب" value={`${money(stats.due)} روپے`} note="دستیاب مہینے" color="amber"/><Card title="وصول شدہ" value={`${money(stats.paid)} روپے`} note="ادائیگیاں" color="green"/><Card title="بقایا" value={`${money(stats.balance)} روپے`} note="قابلِ ادائیگی" color="red"/></section>
  <div className="grid gap-7 lg:grid-cols-2"><Section title="تازہ نوٹس">{data.notices.length?data.notices.map(n=><Item key={String(n.id)} title={String(n.title)} text={String(n.message)} meta={`${String(n.notice_type)} • ${date(n.published_at)}`}/>):<Empty/>}</Section><Section title="روزانہ حاضری"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{data.attendance.slice(0,18).map(a=><div key={String(a.id)} className="rounded-xl border p-3"><b>{date(a.attendance_date)}</b><p className={a.attendance_status==="حاضر"?"text-green-700":"text-red-700"}>{String(a.attendance_status)}</p></div>)}</div>{!data.attendance.length&&<Empty/>}</Section></div>
  <div className="grid gap-7 lg:grid-cols-2"><Section title="فیس و واجبات">{data.fees.slice(0,12).map(f=><Item key={String(f.id)} title={`${String(f.fee_month)} — ${String(f.fee_type)}`} text={`واجب: ${money(f.amount_due)} | وصول: ${money(f.amount_paid)} | بقایا: ${money(Number(f.amount_due)-Number(f.amount_paid))}`} meta={f.receipt_number?`رسید: ${String(f.receipt_number)}`:"ادائیگی زیرِ انتظار"}/>) }{!data.fees.length&&<Empty/>}</Section><Section title="امتحانی نتائج">{data.results.slice(0,15).map(r=>{const sub=(r.exam_subjects||{}) as Row,exam=(r.exams||{}) as Row;return <Item key={String(r.id)} title={`${String(exam.exam_name||"امتحان")} — ${String(sub.subject_name||"مضمون")}`} text={r.absent?"غیر حاضر":`${money(r.obtained_marks)} از ${money(sub.total_marks)}`} meta={String(exam.status||"")}/>})}{!data.results.length&&<Empty/>}</Section></div>
  <div className="grid gap-7 lg:grid-cols-2"><Section title="رخصت و نظم و ضبط">{data.leaves.slice(0,10).map(x=><Item key={String(x.id)} title={`${String(x.record_type)} — ${String(x.status)}`} text={String(x.reason)} meta={`${date(x.start_date)} تا ${date(x.end_date)}`}/>) }{!data.leaves.length&&<Empty/>}</Section><Section title="ہاسٹل اور آمد و روانگی">{data.hostel.slice(0,1).map(x=><Item key={String(x.id)} title={`کمرہ ${String(x.room_number)} — ${String(x.block_name)}`} text={`بیڈ: ${String(x.bed_number||"—")}`} meta={String(x.status)}/>)}{data.gate.slice(0,6).map(x=><Item key={String(x.id)} title={`${String(x.movement_type)} — ${date(x.movement_at)}`} text={String(x.purpose)} meta={String(x.guardian_name||"")}/>)}{!data.hostel.length&&!data.gate.length&&<Empty/>}</Section></div>
 </div></main>}
function Card({title,value,note,color}:{title:string;value:string;note:string;color:string}){const colors:Record<string,string>={blue:"border-blue-500",amber:"border-amber-500",green:"border-green-500",red:"border-red-500"};return <div className={`rounded-2xl border-r-4 bg-white p-5 shadow ${colors[color]}`}><p className="text-slate-500">{title}</p><b className="mt-2 block text-2xl">{value}</b><small className="text-slate-400">{note}</small></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="rounded-2xl bg-white p-6 shadow"><h3 className="mb-4 text-xl font-black text-blue-950">{title}</h3><div className="space-y-3">{children}</div></section>}
function Item({title,text,meta}:{title:string;text:string;meta:string}){return <div className="rounded-xl border border-slate-200 p-4"><b>{title}</b><p className="mt-1 text-slate-700">{text}</p><small className="text-slate-400">{meta}</small></div>}
function Empty(){return <p className="rounded-xl bg-slate-50 p-4 text-slate-500">ابھی کوئی ریکارڈ موجود نہیں۔</p>}
