import { NextRequest, NextResponse } from "next/server";
import * as XLSX from "xlsx";
import JSZip from "jszip";
import { adminDb, isAuthorizedAdmin } from "@/lib/admin-db";

export const runtime = "nodejs";
export const maxDuration = 60;

type Raw = Record<string, unknown>;
const aliases: Record<string, string[]> = {
  studentName: ["طالب علم کا نام","طالبعلم کا نام","طالب علم","نام","student name","studentname","name"], fatherName: ["والد کا نام","والد","ولدیت","father name","fathername"],
  phone: ["موبائل نمبر","فون نمبر","واٹس ایپ نمبر","موبائل","فون","phone","mobile","whatsapp"], studentNumber: ["طالب علم نمبر","داخلہ نمبر","رجسٹریشن نمبر","student number","admission no","roll no"],
  department: ["شعبہ","کورس","department","course"], className: ["جماعت","کلاس","درجہ","class","classname"], address: ["پتہ","مکمل پتہ","address"],
  dateOfBirth: ["تاریخ پیدائش","تاریخِ پیدائش","date of birth","dob"], gender: ["جنس","gender"], email: ["ای میل","email"], joinedAt: ["تاریخ داخلہ","داخلہ تاریخ","joined at","admission date"]
};
const clean = (v: unknown) => String(v ?? "").replace(/\s+/g, " ").trim();
const normalized = (v: string) => v.toLowerCase().replace(/[\s_\-.:()]/g, "");
function value(row: Raw, field: string) { const names = aliases[field].map(normalized); const key = Object.keys(row).find(k=>names.includes(normalized(k))); return key ? clean(row[key]) : ""; }
function mappedRows(raw: Raw[]) { return raw.filter(r=>Object.values(r).some(v=>clean(v))).map((r,i)=>{ const item = { rowNumber:i+2, studentName:value(r,"studentName"), fatherName:value(r,"fatherName"), phone:value(r,"phone").replace(/[^0-9+]/g,""), studentNumber:value(r,"studentNumber"), department:value(r,"department"), className:value(r,"className"), address:value(r,"address"), dateOfBirth:value(r,"dateOfBirth"), gender:value(r,"gender"), email:value(r,"email"), joinedAt:value(r,"joinedAt") }; const errors=[]; if(!item.studentName) errors.push("نام موجود نہیں"); if(!item.fatherName) errors.push("والد کا نام موجود نہیں"); if(!item.department) errors.push("شعبہ موجود نہیں"); if(item.phone && item.phone.replace(/\D/g,"").length<10) errors.push("موبائل نمبر نامکمل"); return {...item,valid:errors.length===0,errors}; }); }
function xmlText(xml: string) { return xml.replace(/<w:tab\/>/g," ").replace(/<w:br\/>/g,"\n").replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").trim(); }
async function parseDocx(buffer: ArrayBuffer): Promise<Raw[]> { const zip=await JSZip.loadAsync(buffer); const xml=await zip.file("word/document.xml")?.async("string"); if(!xml) throw new Error("Word file invalid"); const tables=[...xml.matchAll(/<w:tbl[\s\S]*?<\/w:tbl>/g)]; if(!tables.length) throw new Error("Word فائل میں جدول موجود نہیں۔ ریکارڈ کو Table میں رکھیے۔"); const all: Raw[]=[]; for(const table of tables){ const trs=[...table[0].matchAll(/<w:tr[\s\S]*?<\/w:tr>/g)].map(m=>[...m[0].matchAll(/<w:tc[\s\S]*?<\/w:tc>/g)].map(c=>xmlText(c[0]))); if(trs.length<2) continue; const headers=trs[0]; for(const cells of trs.slice(1)){ const row:Raw={}; headers.forEach((h,i)=>row[h]=cells[i]||""); all.push(row); } } return all; }

export async function POST(request: NextRequest) {
  if (!(await isAuthorizedAdmin(request))) return NextResponse.json({success:false},{status:401});
  try { const form=await request.formData(); const mode=String(form.get("mode")||"preview");
    if(mode==="preview") { const file=form.get("file"); if(!(file instanceof File)) return NextResponse.json({success:false,message:"فائل منتخب کریں۔"},{status:400}); if(file.size>15*1024*1024) return NextResponse.json({success:false,message:"فائل 15 MB سے بڑی نہیں ہونی چاہیے۔"},{status:400}); const ext=file.name.split(".").pop()?.toLowerCase(); let raw:Raw[]=[]; const buffer=await file.arrayBuffer(); if(ext==="docx") raw=await parseDocx(buffer); else if(["xlsx","xls","csv"].includes(ext||"")){ const wb=XLSX.read(buffer,{type:"array",cellDates:true}); raw=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:"",raw:false}); } else return NextResponse.json({success:false,message:"صرف Word، Excel یا CSV فائل قبول ہے۔"},{status:400}); const rows=mappedRows(raw); return NextResponse.json({success:true,fileName:file.name,rows,summary:{total:rows.length,valid:rows.filter(r=>r.valid).length,invalid:rows.filter(r=>!r.valid).length}}); }
    const rows=JSON.parse(String(form.get("rows")||"[]")); if(!Array.isArray(rows)||!rows.length) return NextResponse.json({success:false,message:"درآمد کے لیے درست ریکارڈ موجود نہیں۔"},{status:400}); const db=adminDb(); const {data:existing,error:ee}=await db.from("students").select("student_number,phone"); if(ee) throw ee; const numbers=new Set((existing||[]).map(x=>x.student_number).filter(Boolean)); const phones=new Set((existing||[]).map(x=>String(x.phone||"").replace(/\D/g,"")).filter(Boolean)); let imported=0,skipped=0; const year=new Date().getFullYear();
    for(let i=0;i<rows.length;i++){ const r=rows[i], digits=String(r.phone||"").replace(/\D/g,""); if((r.studentNumber&&numbers.has(r.studentNumber))||(digits&&phones.has(digits))){skipped++;continue;} let number=clean(r.studentNumber); if(!number){ number=`JB-${year}-${String(Date.now()).slice(-6)}${String(i).padStart(3,"0")}`; } const {data:student,error}=await db.from("students").insert({student_number:number,student_name:clean(r.studentName),father_name:clean(r.fatherName),phone:clean(r.phone)||null,email:clean(r.email)||null,date_of_birth:/^\d{4}-\d{2}-\d{2}$/.test(r.dateOfBirth)?r.dateOfBirth:null,gender:clean(r.gender)||null,address:clean(r.address)||null,current_department:clean(r.department),student_status:"فعال",joined_at:/^\d{4}-\d{2}-\d{2}$/.test(r.joinedAt)?r.joinedAt:new Date().toISOString().slice(0,10)}).select("id").single(); if(error){skipped++;continue;} await db.from("student_sessions").insert({student_id:student.id,academic_session:`${year}-${year+1}`,department:clean(r.department),class_name:clean(r.className)||null,session_status:"جاری"}); imported++; numbers.add(number); if(digits) phones.add(digits); }
    await db.from("student_import_logs").insert({file_name:clean(form.get("fileName")),total_rows:rows.length,imported_rows:imported,skipped_rows:skipped}); return NextResponse.json({success:true,imported,skipped});
  } catch(error){ console.error("Student import error",error); return NextResponse.json({success:false,message:error instanceof Error?error.message:"فائل درآمد نہیں ہوسکی۔"},{status:500}); }
}
