"use client";
import { FormEvent, useEffect, useState } from "react";

const permissionLabels: Record<string,string> = {dashboard:"ڈیش بورڈ",admissions:"داخلہ",students:"طلبہ",attendance:"حاضری",fees:"فیس",exams:"امتحانات",faculty:"اساتذہ و ٹائم ٹیبل",discipline:"رخصت و نظم",hostel:"ہاسٹل",portal_accounts:"والدین پورٹل",library:"لائبریری",payroll:"تنخواہ",documents:"اسناد",notifications:"اطلاعات",student_import:"طلبہ درآمد",news:"خبریں",settings:"سیٹنگز",users:"صارفین و اختیارات"};
const rolePresets: Record<string,string[]> = {
  manager:Object.keys(permissionLabels), accountant:["dashboard","fees","payroll","notifications"], teacher:["dashboard","students","attendance","exams","discipline"],
  warden:["dashboard","students","attendance","discipline","hostel","notifications"], librarian:["dashboard","students","library","notifications"], clerk:["dashboard","admissions","students","student_import","documents","notifications"], custom:["dashboard"]
};
type User={id:string;username:string;full_name:string;role:string;permissions:string[];is_active:boolean;last_login_at?:string};
export default function AdminUsersManager(){
 const [users,setUsers]=useState<User[]>([]),[message,setMessage]=useState(""),[form,setForm]=useState({fullName:"",username:"",password:"",role:"clerk",permissions:rolePresets.clerk});
 async function load(){const r=await fetch("/api/admin/users");const x=await r.json();if(x.success)setUsers(x.users);else setMessage(x.message||"ریکارڈ حاصل نہیں ہوسکا۔");}
 useEffect(()=>{load()},[]);
 async function submit(e:FormEvent){e.preventDefault();setMessage("");const r=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const x=await r.json();setMessage(x.success?"صارف کامیابی سے بن گیا۔":x.message);if(x.success){setForm({...form,fullName:"",username:"",password:""});load();}}
 async function toggle(u:User){await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:u.id,isActive:!u.is_active})});load();}
 return <div className="grid gap-8 xl:grid-cols-[420px_1fr]" dir="rtl"><form onSubmit={submit} className="h-fit space-y-4 rounded-2xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-blue-950">نیا انتظامی صارف</h2>{[["fullName","پورا نام","text"],["username","صارف نام","text"],["password","پاس ورڈ (کم از کم 8 حروف)","password"]].map(([key,label,type])=><label key={key} className="block font-semibold">{label}<input required type={type} value={form[key as keyof typeof form] as string} onChange={e=>setForm({...form,[key]:e.target.value})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"/></label>)}<label className="block font-semibold">عہدہ<select value={form.role} onChange={e=>setForm({...form,role:e.target.value,permissions:rolePresets[e.target.value]||["dashboard"]})} className="mt-2 w-full rounded-xl border px-4 py-3 font-normal"><option value="manager">مدیر</option><option value="accountant">اکاؤنٹنٹ</option><option value="teacher">استاد</option><option value="warden">وارڈن</option><option value="librarian">لائبریرین</option><option value="clerk">کلرک</option><option value="custom">خصوصی اختیارات</option></select></label><div><p className="font-semibold">اجازتیں</p><div className="mt-2 grid grid-cols-2 gap-2">{Object.entries(permissionLabels).map(([key,label])=><label key={key} className="flex gap-2 text-sm"><input type="checkbox" checked={form.permissions.includes(key)} onChange={e=>setForm({...form,permissions:e.target.checked?[...form.permissions,key]:form.permissions.filter(p=>p!==key)})}/>{label}</label>)}</div></div><button className="w-full rounded-xl bg-blue-800 py-3 font-bold text-white">صارف محفوظ کریں</button>{message&&<p className="rounded-xl bg-blue-50 p-3 text-blue-900">{message}</p>}</form><div className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="border-b p-5"><h2 className="text-xl font-bold text-blue-950">انتظامی صارفین</h2></div><div className="overflow-x-auto"><table className="w-full text-right"><thead className="bg-slate-50"><tr><th className="p-4">نام</th><th className="p-4">عہدہ</th><th className="p-4">اختیارات</th><th className="p-4">حیثیت</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-t"><td className="p-4"><b>{u.full_name}</b><div className="text-sm text-slate-500">{u.username}</div></td><td className="p-4">{u.role}</td><td className="max-w-md p-4 text-sm">{u.permissions.map(p=>permissionLabels[p]||p).join("، ")}</td><td className="p-4"><button onClick={()=>toggle(u)} className={`rounded-full px-3 py-1 text-sm ${u.is_active?"bg-green-100 text-green-800":"bg-red-100 text-red-800"}`}>{u.is_active?"فعال":"غیر فعال"}</button></td></tr>)}</tbody></table></div></div></div>;
}
