"use client";

import { useEffect, useMemo, useState } from "react";
type Student = { id:string; student_number:string; student_name:string; father_name:string; current_department:string };
type Attendance = { student_id:string; attendance_status:string; remarks:string|null };
const today = new Date().toISOString().slice(0,10);

export default function AttendanceManager(){
  const [students,setStudents]=useState<Student[]>([]); const [records,setRecords]=useState<Record<string,{status:string;remarks:string}>>({});
  const [date,setDate]=useState(today); const [session,setSession]=useState(""); const [department,setDepartment]=useState("تمام"); const [search,setSearch]=useState(""); const [message,setMessage]=useState(""); const [saving,setSaving]=useState(false); const [loading,setLoading]=useState(true);
  async function load(selected=date){setLoading(true);setMessage("");try{const response=await fetch(`/api/admin/attendance?date=${selected}`,{cache:"no-store"});if(response.status===401){window.location.href="/admin/login";return}const result=await response.json();if(!response.ok)throw new Error(result.message);setStudents(result.students);setSession(result.session);const map:Record<string,{status:string;remarks:string}>={};result.students.forEach((s:Student)=>{const found=result.attendance.find((a:Attendance)=>a.student_id===s.id);map[s.id]={status:found?.attendance_status||"حاضر",remarks:found?.remarks||""}});setRecords(map)}catch(e){setMessage(e instanceof Error?e.message:"حاضری حاصل نہیں ہوسکی۔")}finally{setLoading(false)}}
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[]);
  const departments=["تمام",...Array.from(new Set(students.map(s=>s.current_department)))];
  const visible=useMemo(()=>students.filter(s=>(department==="تمام"||s.current_department===department)&&[s.student_number,s.student_name,s.father_name].join(" ").toLowerCase().includes(search.toLowerCase())),[students,department,search]);
  const counts=Object.values(records).reduce((x,r)=>({...x,[r.status]:(x[r.status]||0)+1}),{} as Record<string,number>);
  function markAll(status:string){setRecords(old=>{const next={...old};visible.forEach(s=>next[s.id]={...next[s.id],status});return next})}
  async function save(){setSaving(true);setMessage("");try{const response=await fetch("/api/admin/attendance",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({date,academicSession:session,records:visible.map(s=>({studentId:s.id,status:records[s.id]?.status||"حاضر",remarks:records[s.id]?.remarks||""}))})});const result=await response.json();if(!response.ok)throw new Error(result.message);setMessage(`${result.count} طلبہ کی حاضری محفوظ ہوگئی۔`)}catch(e){setMessage(e instanceof Error?e.message:"حاضری محفوظ نہیں ہوسکی۔")}finally{setSaving(false)}}
  return <div dir="rtl" className="space-y-5"><div className="grid gap-3 md:grid-cols-4">{["حاضر","غیر حاضر","رخصت","تاخیر"].map(x=><div key={x} className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-slate-500">{x}</p><p className="text-3xl font-black">{counts[x]||0}</p></div>)}</div>
    <section className="rounded-2xl bg-white p-4 shadow-sm"><div className="grid gap-3 md:grid-cols-4"><input type="date" value={date} onChange={e=>{setDate(e.target.value);void load(e.target.value)}} className="rounded-xl border p-3"/><select value={department} onChange={e=>setDepartment(e.target.value)} className="rounded-xl border p-3">{departments.map(x=><option key={x}>{x}</option>)}</select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="نام یا طالب علم نمبر" className="rounded-xl border p-3 md:col-span-2"/></div><div className="mt-4 flex flex-wrap gap-2"><span className="py-2 text-sm text-slate-500">سب کو نشان لگائیں:</span>{["حاضر","غیر حاضر","رخصت","تاخیر"].map(x=><button key={x} onClick={()=>markAll(x)} className="rounded-lg bg-slate-100 px-3 py-2 text-sm">{x}</button>)}</div></section>
    {message&&<div className="rounded-xl bg-blue-50 p-4 text-blue-900">{message}</div>}
    <section className="overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="min-w-full text-right text-sm"><thead className="bg-slate-100"><tr>{["طالب علم","والد","شعبہ","حاضری","نوٹس"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={5} className="p-10 text-center">لوڈ ہورہا ہے…</td></tr>:visible.map(s=><tr key={s.id} className="border-t"><td className="p-3"><b>{s.student_name}</b><small className="block text-slate-500">{s.student_number}</small></td><td className="p-3">{s.father_name}</td><td className="p-3">{s.current_department}</td><td className="p-3"><select value={records[s.id]?.status||"حاضر"} onChange={e=>setRecords({...records,[s.id]:{...records[s.id],status:e.target.value}})} className="rounded-lg border p-2"><option>حاضر</option><option>غیر حاضر</option><option>رخصت</option><option>تاخیر</option></select></td><td className="p-3"><input value={records[s.id]?.remarks||""} onChange={e=>setRecords({...records,[s.id]:{...records[s.id],remarks:e.target.value}})} placeholder="اختیاری" className="rounded-lg border p-2"/></td></tr>)}</tbody></table></section>
    <div className="sticky bottom-4 flex justify-end"><button onClick={()=>void save()} disabled={saving||visible.length===0} className="rounded-xl bg-blue-900 px-7 py-3 font-bold text-white shadow-lg disabled:opacity-50">{saving?"محفوظ ہورہا ہے…":`${visible.length} طلبہ کی حاضری محفوظ کریں`}</button></div>
  </div>
}
