"use client";

import { useEffect, useMemo, useState } from "react";

type Subject={id:string;subject_name:string;total_marks:number;passing_marks:number;display_order:number};
type Exam={id:string;exam_name:string;academic_session:string;department:string;class_name:string;exam_date:string|null;status:string;exam_subjects:Subject[]};
type Student={student_id:string;roll_number:string|null;students:{id:string;student_number:string;student_name:string;father_name:string}};
type Result={student_id:string;subject_id:string;obtained_marks:number|null;absent:boolean;remarks:string|null};
type Mark={marks:string;absent:boolean;remarks:string};

const blankSubject={name:"",total:100,passing:40};

export default function ExamResultsManager(){
  const [session,setSession]=useState(""); const [exams,setExams]=useState<Exam[]>([]); const [exam,setExam]=useState<Exam|null>(null);
  const [students,setStudents]=useState<Student[]>([]); const [marks,setMarks]=useState<Record<string,Mark>>({});
  const [form,setForm]=useState({examName:"ششماہی امتحان",department:"",className:"",examDate:"",subjects:[{...blankSubject}]});
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState("");

  async function load(examId?:string){setLoading(true);setMessage("");try{const url=`/api/admin/exams?session=${encodeURIComponent(session)}${examId?`&examId=${examId}`:""}`;const response=await fetch(url,{cache:"no-store"});if(response.status===401){location.href="/admin/login";return}const data=await response.json();if(!response.ok)throw new Error(data.message);setSession(data.session);setExams(data.exams);if(data.exam){setExam(data.exam);setStudents(data.students);const next:Record<string,Mark>={};(data.results as Result[]).forEach(r=>next[`${r.student_id}:${r.subject_id}`]={marks:r.obtained_marks===null?"":String(r.obtained_marks),absent:r.absent,remarks:r.remarks||""});setMarks(next)}}catch(e){setMessage(e instanceof Error?e.message:"ریکارڈ حاصل نہیں ہوسکا۔")}finally{setLoading(false)}}
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[]);

  function updateSubject(index:number,key:"name"|"total"|"passing",value:string){setForm(x=>({...x,subjects:x.subjects.map((s,i)=>i===index?{...s,[key]:key==="name"?value:Number(value)}:s)}))}
  async function createExam(){setSaving(true);setMessage("");try{const response=await fetch("/api/admin/exams",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,academicSession:session})});const data=await response.json();if(!response.ok)throw new Error(data.message);setMessage("امتحان اور مضامین محفوظ ہوگئے۔");await load(data.exam.id)}catch(e){setMessage(e instanceof Error?e.message:"امتحان محفوظ نہیں ہوسکا۔")}finally{setSaving(false)}}
  function setMark(studentId:string,subjectId:string,patch:Partial<Mark>){const key=`${studentId}:${subjectId}`;setMarks(x=>{const previous=x[key]||{marks:"",absent:false,remarks:""};return {...x,[key]:{...previous,...patch}}})}
  async function saveResults(){if(!exam)return;setSaving(true);setMessage("");try{const results=students.flatMap(s=>subjects.map(subject=>({studentId:s.student_id,subjectId:subject.id,...(marks[`${s.student_id}:${subject.id}`]||{marks:"",absent:false,remarks:""})})));for(const row of results){const subject=subjects.find(x=>x.id===row.subjectId)!;if(row.marks!==""&&(Number(row.marks)<0||Number(row.marks)>Number(subject.total_marks)))throw new Error(`${subject.subject_name} کے نمبر کل نمبروں سے زیادہ ہیں۔`)}const response=await fetch("/api/admin/exams",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"saveResults",examId:exam.id,results})});const data=await response.json();if(!response.ok)throw new Error(data.message);setMessage("تمام طلبہ کے نمبر کامیابی سے محفوظ ہوگئے۔");await load(exam.id)}catch(e){setMessage(e instanceof Error?e.message:"نمبر محفوظ نہیں ہوسکے۔")}finally{setSaving(false)}}
  const subjects=useMemo(()=>[...(exam?.exam_subjects||[])].sort((a,b)=>a.display_order-b.display_order),[exam]);
  const summaries=useMemo(()=>students.map(s=>{let obtained=0,total=0,failed=0,complete=true;subjects.forEach(subject=>{const mark=marks[`${s.student_id}:${subject.id}`];total+=Number(subject.total_marks);if(!mark||(!mark.absent&&mark.marks==="")){complete=false;return}const score=mark.absent?0:Number(mark.marks);obtained+=score;if(mark.absent||score<Number(subject.passing_marks))failed++});return{student:s,obtained,total,failed,complete,percent:total?obtained/total*100:0}}).sort((a,b)=>b.obtained-a.obtained),[students,subjects,marks]);
  const positions=useMemo(()=>{let rank=0,last:number|null=null;return summaries.map((x,i)=>{if(x.complete&&x.failed===0&&x.obtained!==last)rank=i+1;last=x.obtained;return{...x,position:x.complete&&x.failed===0?rank:null}})},[summaries]);
  function grade(p:number,failed:number){if(failed)return"ناکام";if(p>=80)return"ممتاز";if(p>=70)return"بہت اچھا";if(p>=60)return"اچھا";if(p>=50)return"درجہ دوم";return"کامیاب"}
  function printCard(item:(typeof positions)[number]){if(!exam)return;const rows=subjects.map(subject=>{const m=marks[`${item.student.student_id}:${subject.id}`];const score=m?.absent?"غیر حاضر":m?.marks||"—";return`<tr><td>${subject.subject_name}</td><td>${subject.total_marks}</td><td>${subject.passing_marks}</td><td>${score}</td><td>${m?.absent||Number(m?.marks)<Number(subject.passing_marks)?"ناکام":"کامیاب"}</td></tr>`}).join("");openPrint(`<h1>جامعہ بلال الاسلامیہ</h1><h2>رزلٹ کارڈ — ${exam.exam_name}</h2><div class="grid"><b>طالب علم: ${item.student.students.student_name}</b><b>والد: ${item.student.students.father_name}</b><b>طالب علم نمبر: ${item.student.students.student_number}</b><b>رول نمبر: ${item.student.roll_number||"—"}</b><b>شعبہ: ${exam.department}</b><b>جماعت: ${exam.class_name||"—"}</b><b>تعلیمی سیشن: ${exam.academic_session}</b><b>تاریخ امتحان: ${exam.exam_date||"—"}</b></div><table><thead><tr><th>مضمون</th><th>کل نمبر</th><th>کامیابی</th><th>حاصل کردہ</th><th>نتیجہ</th></tr></thead><tbody>${rows}</tbody></table><div class="summary"><b>کل: ${item.obtained} / ${item.total}</b><b>فیصد: ${item.percent.toFixed(2)}%</b><b>درجہ: ${grade(item.percent,item.failed)}</b><b>پوزیشن: ${item.position||"—"}</b></div><div class="footer"><span>دستخط ناظم امتحانات</span><span>مہر ادارہ</span><span>دستخط مدیر جامعہ</span></div>`,"رزلٹ کارڈ")}
  function printPositions(){if(!exam)return;const rows=positions.filter(x=>x.complete&&x.failed===0).map(x=>`<tr><td>${x.position}</td><td>${x.student.students.student_name}</td><td>${x.student.students.father_name}</td><td>${x.student.roll_number||"—"}</td><td>${x.obtained}/${x.total}</td><td>${x.percent.toFixed(2)}%</td><td>${grade(x.percent,x.failed)}</td></tr>`).join("");openPrint(`<h1>جامعہ بلال الاسلامیہ</h1><h2>${exam.exam_name} — پوزیشن و نتیجہ فہرست</h2><p>${exam.department} ${exam.class_name?`— ${exam.class_name}`:""} | تعلیمی سیشن: ${exam.academic_session}</p><table><thead><tr><th>پوزیشن</th><th>طالب علم</th><th>والد</th><th>رول نمبر</th><th>نمبر</th><th>فیصد</th><th>درجہ</th></tr></thead><tbody>${rows}</tbody></table><div class="footer"><span>ناظم امتحانات</span><span>مہر ادارہ</span><span>مدیر جامعہ</span></div>`,"پوزیشن فہرست")}

  return <div className="space-y-6">
    <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-4 text-xl font-black">نیا امتحان بنائیں</h2><div className="grid gap-3 md:grid-cols-4"><input value={form.examName} onChange={e=>setForm({...form,examName:e.target.value})} placeholder="امتحان کا نام" className="rounded-xl border p-3"/><input value={form.department} onChange={e=>setForm({...form,department:e.target.value})} placeholder="شعبہ" className="rounded-xl border p-3"/><input value={form.className} onChange={e=>setForm({...form,className:e.target.value})} placeholder="جماعت" className="rounded-xl border p-3"/><input type="date" value={form.examDate} onChange={e=>setForm({...form,examDate:e.target.value})} className="rounded-xl border p-3"/></div><h3 className="mb-2 mt-5 font-bold">مضامین اور نمبر</h3>{form.subjects.map((s,i)=><div key={i} className="mb-2 grid gap-2 md:grid-cols-4"><input value={s.name} onChange={e=>updateSubject(i,"name",e.target.value)} placeholder="مضمون" className="rounded-xl border p-3"/><input type="number" value={s.total} onChange={e=>updateSubject(i,"total",e.target.value)} placeholder="کل نمبر" className="rounded-xl border p-3"/><input type="number" value={s.passing} onChange={e=>updateSubject(i,"passing",e.target.value)} placeholder="کامیابی کے نمبر" className="rounded-xl border p-3"/><button onClick={()=>setForm(x=>({...x,subjects:x.subjects.filter((_,n)=>n!==i)}))} disabled={form.subjects.length===1} className="rounded-xl bg-red-50 p-3 text-red-700 disabled:opacity-40">مضمون حذف کریں</button></div>)}<div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setForm(x=>({...x,subjects:[...x.subjects,{...blankSubject}]}))} className="rounded-xl bg-slate-100 px-5 py-3 font-bold">+ مضمون</button><button onClick={()=>void createExam()} disabled={saving} className="rounded-xl bg-blue-900 px-6 py-3 font-bold text-white disabled:opacity-50">امتحان محفوظ کریں</button></div></section>
    {message&&<p className="rounded-xl bg-blue-50 p-4 text-blue-900">{message}</p>}
    <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-4 text-xl font-black">محفوظ امتحانات</h2><div className="flex flex-wrap gap-2">{exams.map(x=><button key={x.id} onClick={()=>void load(x.id)} className={`rounded-xl border px-4 py-3 ${exam?.id===x.id?"bg-blue-900 text-white":"bg-white"}`}>{x.exam_name} — {x.department}{x.class_name?` / ${x.class_name}`:""}</button>)}{!loading&&!exams.length&&<p className="text-slate-500">ابھی کوئی امتحان موجود نہیں۔</p>}</div></section>
    {exam&&<section className="rounded-2xl bg-white p-4 shadow-sm"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">{exam.exam_name} — نمبر اندراج</h2><p className="text-sm text-slate-500">{exam.department} {exam.class_name&&`/ ${exam.class_name}`} | {exam.academic_session}</p></div><div className="flex gap-2"><button onClick={printPositions} className="rounded-xl bg-amber-100 px-4 py-3 font-bold text-amber-900">پوزیشن فہرست</button><button onClick={()=>void saveResults()} disabled={saving} className="rounded-xl bg-green-700 px-5 py-3 font-bold text-white">تمام نمبر محفوظ کریں</button></div></div><div className="overflow-x-auto"><table className="min-w-full text-right text-sm"><thead className="bg-slate-100"><tr><th className="p-3">طالب علم</th>{subjects.map(s=><th key={s.id} className="min-w-40 p-3">{s.subject_name}<small className="block font-normal">کل {s.total_marks} | کامیابی {s.passing_marks}</small></th>)}<th className="p-3">نتیجہ</th><th className="p-3">کارڈ</th></tr></thead><tbody>{positions.map(item=><tr key={item.student.student_id} className="border-t"><td className="p-3"><b>{item.student.students.student_name}</b><small className="block text-slate-500">{item.student.roll_number||item.student.students.student_number}</small></td>{subjects.map(subject=>{const key=`${item.student.student_id}:${subject.id}`;const m=marks[key]||{marks:"",absent:false,remarks:""};return <td key={subject.id} className="p-2"><div className="flex items-center gap-2"><input type="number" min="0" max={subject.total_marks} disabled={m.absent} value={m.marks} onChange={e=>setMark(item.student.student_id,subject.id,{marks:e.target.value})} className="w-20 rounded-lg border p-2 disabled:bg-slate-100"/><label className="whitespace-nowrap text-xs"><input type="checkbox" checked={m.absent} onChange={e=>setMark(item.student.student_id,subject.id,{absent:e.target.checked,marks:e.target.checked?"":m.marks})}/> غیر حاضر</label></div></td>})}<td className="p-3"><b className={item.failed?"text-red-700":"text-green-700"}>{item.complete?grade(item.percent,item.failed):"نامکمل"}</b><small className="block">{item.obtained}/{item.total} — {item.percent.toFixed(1)}%</small>{item.position&&<small className="font-bold text-blue-800">پوزیشن: {item.position}</small>}</td><td className="p-3"><button disabled={!item.complete} onClick={()=>printCard(item)} className="rounded-lg bg-blue-50 px-3 py-2 text-blue-800 disabled:opacity-40">رزلٹ کارڈ</button></td></tr>)}</tbody></table></div>{!students.length&&<p className="p-8 text-center text-slate-500">اس شعبہ/جماعت کے موجودہ سیشن میں کوئی فعال طالب علم نہیں ملا۔ طلبہ کے سالانہ ریکارڈ میں شعبہ اور جماعت چیک کریں۔</p>}</section>}
  </div>
}

function openPrint(content:string,title:string){const popup=window.open("","_blank","width=900,height=1000");if(!popup)return;popup.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>${title}</title><style>@page{size:A4;margin:14mm}body{font-family:Arial,sans-serif;color:#10213e;text-align:right}h1,h2{text-align:center;margin:6px}.grid,.summary{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:22px 0;padding:15px;background:#f4f7fb;border-radius:10px}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #8492a6;padding:9px;text-align:center}th{background:#173b73;color:white}.summary{grid-template-columns:repeat(4,1fr);font-size:17px;border:2px solid #d4af37}.footer{display:flex;justify-content:space-between;margin-top:65px}.footer span{width:28%;border-top:1px solid;text-align:center;padding-top:8px}@media print{button{display:none}}</style></head><body>${content}<script>window.onload=()=>window.print()</script></body></html>`);popup.document.close()}
