"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { periodTimes, timetableDays } from "@/lib/timetable";

type Teacher={id:string;teacher_name:string;qualification:string;specialization:string;teachable_subjects:string[];available_days:number[];max_periods_daily:number;max_periods_weekly:number;status:string};
type Need={id:string;department:string;class_name:string;subject_name:string;weekly_periods:number;preferred_teacher_id:string|null};
type Period={id:string;department:string;class_name:string;subject_name:string;teacher_id:string|null;day_number:number;period_number:number;faculty_members:{teacher_name:string}|null};
const days=timetableDays;
const box="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm";
const input="w-full rounded-xl border border-slate-300 px-3 py-2.5 outline-none focus:border-blue-600";

export default function FacultyTimetableManager(){
 const [data,setData]=useState<{faculty:Teacher[];requirements:Need[];timetable:Period[];session:string}>({faculty:[],requirements:[],timetable:[],session:"2026-27"});
 const [tab,setTab]=useState<"teachers"|"needs"|"table">("teachers"),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{setLoading(true);const r=await fetch(`/api/admin/faculty?session=${encodeURIComponent(data.session)}`);const j=await r.json();if(j.success)setData(j);else setMsg(j.message);setLoading(false)},[data.session]);
 useEffect(()=>{load()},[load]);
 async function send(body:Record<string,unknown>,method="POST"){setMsg("محفوظ کیا جا رہا ہے…");const r=await fetch("/api/admin/faculty",{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();setMsg(j.message+(j.conflicts?.length?` — ${j.conflicts.join("، ")}`:""));if(j.success)await load()}
 const groups=useMemo(()=>Array.from(new Set(data.timetable.map(x=>`${x.department}|${x.class_name}`))),[data.timetable]);
 if(loading)return <div className={box}>ریکارڈ لوڈ ہو رہا ہے…</div>;
 return <section className="space-y-5">
  <div className="flex flex-wrap items-center gap-2 print:hidden">
   {[["teachers","اساتذہ"],["needs","مضامین و پیریڈ"],["table","ہفتہ وار ٹائم ٹیبل"]].map(([k,l])=><button key={k} onClick={()=>setTab(k as typeof tab)} className={`rounded-xl px-4 py-2.5 font-bold ${tab===k?"bg-blue-900 text-white":"bg-white text-slate-700 shadow-sm"}`}>{l}</button>)}
   <label className="mr-auto flex items-center gap-2">سیشن<input className="w-28 rounded-lg border p-2" value={data.session} onChange={e=>setData({...data,session:e.target.value})}/></label>
  </div>
  {msg&&<div className="rounded-xl bg-amber-50 p-3 text-amber-900 print:hidden">{msg}</div>}
  {tab==="teachers"&&<><TeacherForm onSave={send}/><div className={box}><h2 className="mb-4 text-xl font-black">اساتذہ کی فہرست</h2><div className="overflow-x-auto"><table className="w-full text-right"><thead className="bg-slate-100"><tr><th className="p-3">نام</th><th>تعلیم / تخصص</th><th>مضامین</th><th>دستیابی</th><th>حد</th></tr></thead><tbody>{data.faculty.map(t=><tr className="border-b" key={t.id}><td className="p-3 font-bold">{t.teacher_name}</td><td>{t.qualification}<br/><span className="text-slate-500">{t.specialization}</span></td><td>{t.teachable_subjects?.join("، ")||"تمام"}</td><td>{t.available_days?.map(d=>days[d]).join("، ")}</td><td>{t.max_periods_daily} روزانہ / {t.max_periods_weekly} ہفتہ</td></tr>)}</tbody></table></div></div></>}
  {tab==="needs"&&<><NeedForm session={data.session} teachers={data.faculty} onSave={send}/><div className={box}><h2 className="mb-4 text-xl font-black">تدریسی ضرورتیں</h2>{data.requirements.map(n=><div key={n.id} className="mb-2 flex flex-wrap justify-between rounded-xl bg-slate-50 p-3"><b>{n.department} — {n.class_name} — {n.subject_name}</b><span>{n.weekly_periods} پیریڈ فی ہفتہ</span></div>)}</div></>}
  {tab==="table"&&<><div className={`${box} print:hidden`}><h2 className="text-xl font-black">جامعہ کا اصل PDF ٹائم ٹیبل</h2><p className="mt-1 text-slate-600">ہفتہ تا جمعرات، دس جماعتیں اور آٹھ پیریڈ ایک کلک سے درج کریں۔</p><button onClick={()=>send({action:"import_jamia_schedule",academicSession:data.session})} className="mt-4 rounded-xl bg-amber-500 px-6 py-3 font-black text-blue-950">PDF کا مکمل جدول ابھی درج کریں</button></div><PeriodForm session={data.session} teachers={data.faculty} onSave={send}/><div className={`${box} flex flex-wrap items-end gap-3 print:hidden`}><label>روزانہ پیریڈ<input id="period-count" type="number" defaultValue="8" min="1" max="8" className={`${input} mt-1 w-28`}/></label><button onClick={()=>send({action:"generate",academicSession:data.session,periodsPerDay:Number((document.getElementById("period-count") as HTMLInputElement).value)},"PATCH")} className="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">خودکار ٹائم ٹیبل بنائیں</button><button onClick={()=>window.print()} className="rounded-xl bg-slate-800 px-5 py-3 font-bold text-white">پرنٹ / PDF</button></div><div className="hidden text-center print:block"><h1 className="text-2xl font-black">جامعہ بلال الاسلامیہ</h1><p>ہفتہ وار نظام الاوقات — {data.session}</p></div>{groups.length?groups.map(g=><Timetable key={g} group={g} rows={data.timetable}/>):<div className={box}>ابھی ٹائم ٹیبل نہیں بنایا گیا۔ پہلے اساتذہ اور مضامین محفوظ کریں۔</div>}</>}
 </section>
}

function TeacherForm({onSave}:{onSave:(x:Record<string,unknown>)=>void}){const [subjects,setSubjects]=useState("");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);onSave({action:"teacher",teacherName:f.get("name"),fatherName:f.get("father"),phone:f.get("phone"),qualification:f.get("qualification"),specialization:f.get("specialization"),subjects:subjects.split("،").flatMap(x=>x.split(",")),availableDays:f.getAll("days").map(Number),maxDaily:Number(f.get("daily")),maxWeekly:Number(f.get("weekly")),employmentType:f.get("type")})}return <form onSubmit={submit} className={`${box} grid gap-3 md:grid-cols-3`}><h2 className="text-xl font-black md:col-span-3">نیا استاد درج کریں</h2><input required name="name" className={input} placeholder="استاد کا نام"/><input name="father" className={input} placeholder="والد کا نام"/><input name="phone" className={input} placeholder="موبائل نمبر"/><input name="qualification" className={input} placeholder="تعلیمی قابلیت"/><input name="specialization" className={input} placeholder="تخصص"/><input value={subjects} onChange={e=>setSubjects(e.target.value)} className={input} placeholder="مضامین، کوما سے الگ"/><div className="md:col-span-3"><b>دستیاب دن: </b>{days.slice(1).map((d,i)=><label key={d} className="ml-4"><input type="checkbox" name="days" value={i+1} defaultChecked/> {d}</label>)}</div><label>روزانہ زیادہ سے زیادہ<input name="daily" type="number" defaultValue="5" className={input}/></label><label>ہفتہ وار زیادہ سے زیادہ<input name="weekly" type="number" defaultValue="24" className={input}/></label><label>ملازمت<select name="type" className={input}><option>کل وقتی</option><option>جز وقتی</option><option>وزٹنگ</option></select></label><button className="rounded-xl bg-blue-900 px-5 py-3 font-bold text-white md:col-span-3">استاد محفوظ کریں</button></form>}

function NeedForm({session,teachers,onSave}:{session:string;teachers:Teacher[];onSave:(x:Record<string,unknown>)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);onSave({action:"requirement",academicSession:session,department:f.get("department"),className:f.get("class"),subjectName:f.get("subject"),weeklyPeriods:Number(f.get("periods")),preferredTeacherId:f.get("teacher")})}return <form onSubmit={submit} className={`${box} grid gap-3 md:grid-cols-3`}><h2 className="text-xl font-black md:col-span-3">جماعت کا مضمون اور مطلوبہ پیریڈ</h2><input required name="department" className={input} placeholder="شعبہ"/><input required name="class" className={input} placeholder="جماعت"/><input required name="subject" className={input} placeholder="مضمون"/><input required name="periods" type="number" min="1" defaultValue="5" className={input}/><select name="teacher" className={input}><option value="">موزوں استاد خود منتخب ہو</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.teacher_name}</option>)}</select><button className="rounded-xl bg-blue-900 px-5 py-3 font-bold text-white">محفوظ کریں</button></form>}

function PeriodForm({session,teachers,onSave}:{session:string;teachers:Teacher[];onSave:(x:Record<string,unknown>)=>void}){function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);onSave({action:"period",academicSession:session,department:f.get("department"),className:f.get("class"),subjectName:f.get("subject"),teacherId:f.get("teacher"),dayNumber:Number(f.get("day")),periodNumber:Number(f.get("period"))})}return <form onSubmit={submit} className={`${box} grid gap-3 md:grid-cols-4 print:hidden`}><h2 className="text-xl font-black md:col-span-4">PDF کے مطابق پیریڈ دستی طور پر درج کریں</h2><input required name="department" className={input} placeholder="شعبہ، مثلاً اصول الشریعہ"/><input required name="class" className={input} placeholder="جماعت، مثلاً الاولیٰ"/><input required name="subject" className={input} placeholder="مضمون"/><select required name="teacher" className={input}><option value="">استاد منتخب کریں</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.teacher_name}</option>)}</select><select name="day" className={input}>{days.slice(1).map((day,index)=><option key={day} value={index+1}>{day}</option>)}</select><select name="period" className={input}>{periodTimes.map(period=><option key={period.number} value={period.number}>پیریڈ {period.number} — {period.time}</option>)}</select><button className="rounded-xl bg-blue-900 px-5 py-3 font-bold text-white md:col-span-2">پیریڈ محفوظ / تبدیل کریں</button></form>}

function Timetable({group,rows}:{group:string;rows:Period[]}){const [dept,cls]=group.split("|");const list=rows.filter(r=>r.department===dept&&r.class_name===cls);return <div className={box}><h2 className="mb-3 text-center text-xl font-black">{dept} — {cls}</h2><div className="overflow-x-auto"><table className="min-w-[980px] w-full border-collapse text-center text-sm"><thead><tr><th className="border p-2">دن</th>{periodTimes.map(period=><th className="border p-2" key={period.number}>پیریڈ {period.number}<br/><span className="font-normal text-slate-500">{period.time}</span></th>)}</tr></thead><tbody>{days.slice(1).map((d,di)=><tr key={d}><th className="border bg-slate-50 p-2">{d}</th>{periodTimes.map(period=>{const x=list.find(r=>r.day_number===di+1&&r.period_number===period.number);return <td className="border p-2" key={period.number}>{x?<><b>{x.subject_name}</b><br/><span>{x.faculty_members?.teacher_name}</span></>:"—"}</td>})}</tr>)}</tbody></table></div></div>}
