"use client";

import { useEffect, useMemo, useState } from "react";

type Person={id:string;name:string;number:string;department:string;phone:string};
type RawStudent={id:string;student_name:string;student_number:string;current_department:string;phone?:string};
type RawFaculty={id:string;teacher_name:string;specialization?:string;phone?:string};
type RecordRow={id:string;person_type:string;person_id:string;person_name:string;person_number:string|null;department:string|null;contact_number:string|null;record_type:string;start_date:string|null;end_date:string|null;return_date:string|null;reason:string;action_taken:string|null;guardian_notified:boolean;status:string;created_at:string};
const blank={id:"",personType:"طالب علم",personId:"",recordType:"رخصت",startDate:new Date().toISOString().slice(0,10),endDate:new Date().toISOString().slice(0,10),returnDate:"",reason:"",actionTaken:"",guardianNotified:false,status:"زیر غور"};

export default function LeaveDisciplineManager(){
  const [students,setStudents]=useState<Person[]>([]),[faculty,setFaculty]=useState<Person[]>([]),[records,setRecords]=useState<RecordRow[]>([]);
  const [form,setForm]=useState(blank),[session,setSession]=useState(""),[filter,setFilter]=useState("تمام"),[search,setSearch]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true);
  async function load(){setLoading(true);try{const r=await fetch("/api/admin/leave-discipline",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return}const x=await r.json();if(!r.ok)throw new Error(x.message);setRecords(x.records);setSession(x.session);setStudents(x.students.map((s:RawStudent)=>({id:s.id,name:s.student_name,number:s.student_number,department:s.current_department,phone:s.phone||""})));setFaculty(x.faculty.map((f:RawFaculty)=>({id:f.id,name:f.teacher_name,number:`استاد-${f.id.slice(0,8)}`,department:f.specialization||"",phone:f.phone||""})))}catch(e){setMessage(e instanceof Error?e.message:"ریکارڈ حاصل نہیں ہوسکا۔")}finally{setLoading(false)}}
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{void load()},[]);
  const people=form.personType==="طالب علم"?students:faculty;
  const visible=useMemo(()=>records.filter(r=>(filter==="تمام"||r.record_type===filter)&&[r.person_name,r.person_number,r.reason,r.department].join(" ").toLowerCase().includes(search.toLowerCase())),[records,filter,search]);
  const counts={leave:records.filter(r=>r.record_type==="رخصت").length,pending:records.filter(r=>["زیر غور","زیر کارروائی"].includes(r.status)).length,discipline:records.filter(r=>r.record_type==="نظم و ضبط").length,returned:records.filter(r=>r.status==="واپس آگیا").length};
  function changeType(personType:string){setForm({...blank,personType})}
  function edit(r:RecordRow){setForm({id:r.id,personType:r.person_type,personId:r.person_id,recordType:r.record_type,startDate:r.start_date||blank.startDate,endDate:r.end_date||blank.endDate,returnDate:r.return_date||"",reason:r.reason,actionTaken:r.action_taken||"",guardianNotified:r.guardian_notified,status:r.status});window.scrollTo({top:0,behavior:"smooth"})}
  async function save(){const p=people.find(x=>x.id===form.personId);if(!p){setMessage("طالب علم یا استاد منتخب کریں۔");return}setSaving(true);setMessage("");try{const r=await fetch("/api/admin/leave-discipline",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,academicSession:session,personName:p.name,personNumber:p.number,department:p.department,contactNumber:p.phone})});const x=await r.json();if(!r.ok)throw new Error(x.message);setMessage(x.message);setForm({...blank,personType:form.personType});await load()}catch(e){setMessage(e instanceof Error?e.message:"محفوظ نہیں ہوسکا۔")}finally{setSaving(false)}}
  const statuses=form.recordType==="رخصت"?["زیر غور","منظور","مسترد","واپس آگیا"]:["زیر کارروائی","تنبیہ","حل شدہ","معطل"];
  return <div dir="rtl" className="space-y-5">
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["کل رخصتیں",counts.leave],["زیر غور/کارروائی",counts.pending],["نظم و ضبط",counts.discipline],["واپس آگئے",counts.returned]].map(([t,n])=><div key={String(t)} className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-slate-500">{t}</p><p className="text-3xl font-black">{n}</p></div>)}</div>
    <section className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-4 text-xl font-black">{form.id?"ریکارڈ میں تبدیلی":"نیا ریکارڈ"}</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
      <select value={form.personType} onChange={e=>changeType(e.target.value)} className="rounded-xl border p-3"><option>طالب علم</option><option>استاد</option></select>
      <select value={form.personId} onChange={e=>setForm({...form,personId:e.target.value})} className="rounded-xl border p-3"><option value="">{form.personType} منتخب کریں</option>{people.map(p=><option key={p.id} value={p.id}>{p.name} — {p.number}</option>)}</select>
      <select value={form.recordType} onChange={e=>{const type=e.target.value;setForm({...form,recordType:type,status:type==="رخصت"?"زیر غور":"زیر کارروائی"})}} className="rounded-xl border p-3"><option>رخصت</option><option>نظم و ضبط</option></select>
      <select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="rounded-xl border p-3">{statuses.map(x=><option key={x}>{x}</option>)}</select>
      {form.recordType==="رخصت"&&<><label className="text-sm text-slate-600">از تاریخ<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})} className="mt-1 block w-full rounded-xl border p-3"/></label><label className="text-sm text-slate-600">تا تاریخ<input type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})} className="mt-1 block w-full rounded-xl border p-3"/></label><label className="text-sm text-slate-600">اصل واپسی<input type="date" value={form.returnDate} onChange={e=>setForm({...form,returnDate:e.target.value})} className="mt-1 block w-full rounded-xl border p-3"/></label></>}
      <textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder={form.recordType==="رخصت"?"رخصت کی وجہ *":"واقعہ یا شکایت کی تفصیل *"} className="min-h-24 rounded-xl border p-3 xl:col-span-2"/><textarea value={form.actionTaken} onChange={e=>setForm({...form,actionTaken:e.target.value})} placeholder="کی گئی کارروائی / نوٹس" className="min-h-24 rounded-xl border p-3 xl:col-span-2"/>
    </div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><label className="flex items-center gap-2"><input type="checkbox" checked={form.guardianNotified} onChange={e=>setForm({...form,guardianNotified:e.target.checked})}/><span>والدین/سرپرست کو اطلاع دے دی گئی</span></label><div className="flex gap-2">{form.id&&<button onClick={()=>setForm({...blank,personType:form.personType})} className="rounded-xl bg-slate-100 px-5 py-3">منسوخ</button>}<button onClick={()=>void save()} disabled={saving} className="rounded-xl bg-blue-900 px-6 py-3 font-bold text-white disabled:opacity-50">{saving?"محفوظ ہورہا ہے…":"ریکارڈ محفوظ کریں"}</button></div></div></section>
    {message&&<div className="rounded-xl bg-blue-50 p-4 text-blue-900">{message}</div>}
    <section className="rounded-2xl bg-white shadow-sm"><div className="grid gap-3 p-4 md:grid-cols-3"><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border p-3"><option>تمام</option><option>رخصت</option><option>نظم و ضبط</option></select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="نام، نمبر، شعبہ یا وجہ تلاش کریں" className="rounded-xl border p-3 md:col-span-2"/></div><div className="overflow-x-auto"><table className="min-w-full text-right text-sm"><thead className="bg-slate-100"><tr>{["نام","قسم و تاریخ","وجہ/کارروائی","اطلاع","حیثیت","عمل"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={6} className="p-10 text-center">لوڈ ہورہا ہے…</td></tr>:visible.length===0?<tr><td colSpan={6} className="p-10 text-center text-slate-500">کوئی ریکارڈ موجود نہیں۔</td></tr>:visible.map(r=><tr key={r.id} className="border-t align-top"><td className="p-3"><b>{r.person_name}</b><small className="block text-slate-500">{r.person_type} · {r.person_number||"—"}<br/>{r.department||""}</small></td><td className="p-3"><b>{r.record_type}</b>{r.start_date&&<small className="block text-slate-500">{r.start_date} تا {r.end_date}</small>}</td><td className="max-w-xs p-3">{r.reason}{r.action_taken&&<small className="mt-1 block text-slate-500">کارروائی: {r.action_taken}</small>}</td><td className="p-3">{r.guardian_notified?"ہاں":"نہیں"}</td><td className="p-3"><span className="rounded-full bg-blue-50 px-3 py-1 text-blue-900">{r.status}</span></td><td className="p-3"><button onClick={()=>edit(r)} className="rounded-lg bg-slate-100 px-3 py-2">تبدیل کریں</button></td></tr>)}</tbody></table></div></section>
  </div>
}
