"use client";
import { useEffect,useMemo,useState } from "react";
import QRCode from "qrcode";
type Session={academic_session:string;department:string;class_name:string|null;roll_number:string|null;session_status:string};
type Student={id:string;student_number:string;student_name:string;father_name:string;date_of_birth:string|null;current_department:string;student_status:string;student_image_signed_url?:string|null;student_sessions:Session[]};
type Document={id:string;student_id:string;document_type:string;serial_number:string;verification_token:string;academic_session:string|null;department:string|null;class_name:string|null;issue_reason:string;issued_at:string;valid_until:string|null;signatory_name:string;status:string;cancel_reason:string|null;remarks:string|null};
const today=()=>new Date().toISOString().slice(0,10);const types=["شناختی کارڈ","زیرِ تعلیم سرٹیفکیٹ","کردار سرٹیفکیٹ","سندِ تکمیل","سندِ فراغت","نتیجہ تصدیق"];
export default function StudentDocumentsManager(){
 const [data,setData]=useState<{students:Student[];documents:Document[]}>({students:[],documents:[]}),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[search,setSearch]=useState(""),[printDoc,setPrintDoc]=useState<Document|null>(null),[qr,setQr]=useState("");
 const [form,setForm]=useState({studentId:"",documentType:"شناختی کارڈ",academicSession:"",department:"",className:"",issueReason:"اصل اجرا",issuedAt:today(),validUntil:"",signatoryName:"مدیر جامعہ",remarks:""});
 async function load(){setLoading(true);try{const r=await fetch("/api/admin/documents",{cache:"no-store"});if(r.status===401){location.href="/admin/login";return}const x=await r.json();if(!r.ok)throw new Error(x.message);setData(x)}catch(e){setMessage(e instanceof Error?e.message:"ریکارڈ حاصل نہیں ہوسکا۔")}finally{setLoading(false)}}useEffect(()=>{void load()},[]);
 async function save(){setSaving(true);setMessage("");try{const r=await fetch("/api/admin/documents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)}),x=await r.json();if(!r.ok)throw new Error(x.message);setMessage(x.message);await load();setPrintDoc(x.document)}catch(e){setMessage(e instanceof Error?e.message:"محفوظ نہیں ہوسکا۔")}finally{setSaving(false)}}
 async function status(d:Document,next:string){const reason=next==="فعال"?"":prompt("منسوخی/گم ہونے کی وجہ درج کریں:")||"";if(next!=="فعال"&&!reason)return;const r=await fetch("/api/admin/documents",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:d.id,status:next,cancelReason:reason})}),x=await r.json();setMessage(x.message);if(r.ok)await load()}
 function selectStudent(id:string){const s=data.students.find(x=>x.id===id),session=s?.student_sessions?.[0];setForm({...form,studentId:id,academicSession:session?.academic_session||"",department:session?.department||s?.current_department||"",className:session?.class_name||""})}
 useEffect(()=>{if(!printDoc)return;const url=`${location.origin}/verify/${printDoc.verification_token}`;QRCode.toDataURL(url,{width:180,margin:1}).then(setQr)},[printDoc]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return data.documents.filter(d=>{const s=data.students.find(x=>x.id===d.student_id);return !q||`${d.serial_number} ${d.document_type} ${s?.student_name||""} ${s?.student_number||""}`.toLowerCase().includes(q)})},[data,search]);const input="rounded-xl border border-slate-200 bg-white p-3";
 return <><div className="space-y-5" dir="rtl"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[["کل دستاویزات",data.documents.length],["فعال",data.documents.filter(x=>x.status==="فعال").length],["شناختی کارڈ",data.documents.filter(x=>x.document_type==="شناختی کارڈ").length],["منسوخ/گم",data.documents.filter(x=>x.status!=="فعال").length]].map(([k,v])=><div key={k} className="rounded-2xl bg-white p-4 shadow-sm"><p className="text-slate-500">{k}</p><p className="text-2xl font-black">{v}</p></div>)}</div>{message&&<div className="rounded-xl bg-blue-50 p-4 text-blue-900">{message}</div>}
 <form onSubmit={e=>{e.preventDefault();void save()}} className="rounded-2xl bg-white p-5 shadow-sm"><h2 className="mb-4 text-xl font-black">نئی دستاویز جاری کریں</h2><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><select required value={form.studentId} onChange={e=>selectStudent(e.target.value)} className={input}><option value="">طالب علم منتخب کریں *</option>{data.students.map(s=><option key={s.id} value={s.id}>{s.student_name} — {s.student_number}</option>)}</select><select value={form.documentType} onChange={e=>setForm({...form,documentType:e.target.value})} className={input}>{types.map(x=><option key={x}>{x}</option>)}</select><input value={form.academicSession} onChange={e=>setForm({...form,academicSession:e.target.value})} placeholder="تعلیمی سیشن" className={input}/><input value={form.department} onChange={e=>setForm({...form,department:e.target.value})} placeholder="شعبہ" className={input}/><input value={form.className} onChange={e=>setForm({...form,className:e.target.value})} placeholder="جماعت" className={input}/><select value={form.issueReason} onChange={e=>setForm({...form,issueReason:e.target.value})} className={input}><option>اصل اجرا</option><option>دوبارہ اجرا</option><option>تصحیح کے بعد اجرا</option></select><label className="text-sm text-slate-600">تاریخ اجرا<input required type="date" value={form.issuedAt} onChange={e=>setForm({...form,issuedAt:e.target.value})} className={`${input} mt-1 w-full`}/></label><label className="text-sm text-slate-600">میعاد (اختیاری)<input type="date" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})} className={`${input} mt-1 w-full`}/></label><input value={form.signatoryName} onChange={e=>setForm({...form,signatoryName:e.target.value})} placeholder="دستخط کنندہ" className={input}/><input value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})} placeholder="اضافی نوٹس" className={`${input} md:col-span-2`}/></div><button disabled={saving} className="mt-4 rounded-xl bg-blue-900 px-7 py-3 font-bold text-white">{saving?"جاری ہورہی ہے…":"دستاویز جاری کریں"}</button></form>
 <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="سیریل نمبر، طالب علم نمبر، نام یا دستاویز تلاش کریں" className={`${input} w-full`}/>{loading?<div className="rounded-2xl bg-white p-10 text-center">لوڈ ہورہا ہے…</div>:<section className="overflow-x-auto rounded-2xl bg-white shadow-sm"><table className="min-w-full text-right text-sm"><thead className="bg-slate-100"><tr>{["سیریل نمبر","طالب علم","دستاویز","اجرا","حیثیت","عمل"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{filtered.map(d=>{const s=data.students.find(x=>x.id===d.student_id);return <tr key={d.id} className="border-t"><td className="p-3 font-mono">{d.serial_number}</td><td className="p-3 font-bold">{s?.student_name}<small className="block text-slate-500">{s?.student_number}</small></td><td className="p-3">{d.document_type}<small className="block text-slate-500">{d.issue_reason}</small></td><td className="p-3">{d.issued_at}</td><td className="p-3">{d.status}</td><td className="p-3"><div className="flex flex-wrap gap-2"><button onClick={()=>setPrintDoc(d)} className="rounded-lg bg-blue-50 px-3 py-2 text-blue-900">پرنٹ</button>{d.status==="فعال"?<><button onClick={()=>void status(d,"منسوخ")} className="rounded-lg bg-rose-50 px-3 py-2 text-rose-700">منسوخ</button><button onClick={()=>void status(d,"گم شدہ")} className="rounded-lg bg-amber-50 px-3 py-2 text-amber-700">گم شدہ</button></>:<button onClick={()=>void status(d,"فعال")} className="rounded-lg bg-emerald-50 px-3 py-2 text-emerald-700">بحال</button>}</div></td></tr>})}</tbody></table></section>}</div>{printDoc&&<Printable document={printDoc} student={data.students.find(x=>x.id===printDoc.student_id)} qr={qr} onClose={()=>setPrintDoc(null)}/>}</>;
}
function Printable({document:d,student:s,qr,onClose}:{document:Document;student?:Student;qr:string;onClose:()=>void}){const isCard=d.document_type==="شناختی کارڈ";return <div className="fixed inset-0 z-50 overflow-y-auto bg-slate-950/60 p-4"><section id="student-document" dir="rtl" className={`mx-auto bg-white text-slate-900 ${isCard?"mt-12 max-w-2xl rounded-3xl p-6":"max-w-4xl border-[12px] border-double border-blue-950 p-12"}`}><header className="border-b-2 border-amber-600 pb-4 text-center"><h1 className="text-3xl font-black text-blue-950">جامعہ بلال الاسلامیہ</h1><p>لاہور، پاکستان</p></header>{isCard?<div className="mt-5 flex gap-5"><div className="h-40 w-32 overflow-hidden rounded-xl bg-slate-100">{s?.student_image_signed_url?<img src={s.student_image_signed_url} alt="طالب علم" className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-slate-400">تصویر</div>}</div><div className="flex-1 space-y-2"><h2 className="text-2xl font-black">طالب علم شناختی کارڈ</h2><p><b>نام:</b> {s?.student_name}</p><p><b>والد:</b> {s?.father_name}</p><p><b>طالب علم نمبر:</b> {s?.student_number}</p><p><b>شعبہ/جماعت:</b> {d.department} {d.class_name}</p><p><b>میعاد:</b> {d.valid_until||"تاحکمِ ثانی"}</p></div>{qr&&<img src={qr} alt="تصدیقی QR" className="h-28 w-28"/>}</div>:<div className="py-12 text-center"><h2 className="text-4xl font-black text-blue-950">{d.document_type}</h2><p className="mx-auto mt-10 max-w-3xl text-xl leading-10">تصدیق کی جاتی ہے کہ <b>{s?.student_name}</b> ولد <b>{s?.father_name}</b>، طالب علم نمبر <b>{s?.student_number}</b>، جامعہ بلال الاسلامیہ کے شعبہ <b>{d.department||"—"}</b>، جماعت <b>{d.class_name||"—"}</b>، تعلیمی سیشن <b>{d.academic_session||"—"}</b> سے متعلق یہ مستند دستاویز رکھتا ہے۔</p>{d.remarks&&<p className="mt-5">{d.remarks}</p>}</div>}<footer className="mt-8 grid grid-cols-3 items-end gap-8"><div><p className="font-mono text-xs">{d.serial_number}</p><p>تاریخ اجرا: {d.issued_at}</p></div><div className="text-center"><div className="mx-auto mb-2 h-16 w-28 rounded-full border-2 border-blue-900 pt-5 text-xs font-bold text-blue-900">ادارے کی مہر</div></div><div className="border-t pt-2 text-center"><b>{d.signatory_name}</b><p>دستخط</p></div></footer>{!isCard&&qr&&<div className="mt-5 text-center"><img src={qr} alt="تصدیقی QR" className="mx-auto h-28 w-28"/><p className="text-xs">آن لائن تصدیق کے لیے اسکین کریں</p></div>}<div className="no-print mt-8 flex justify-center gap-2"><button onClick={()=>window.print()} className="rounded-xl bg-blue-900 px-6 py-3 text-white">پرنٹ / PDF</button><button onClick={onClose} className="rounded-xl bg-slate-100 px-6 py-3">بند کریں</button></div></section></div>}
