"use client";
import { useEffect, useState } from "react";

type Data = {logs:Array<{id:number;username:string;action:string;module:string;record_id?:string;created_at:string}>;backups:Array<{id:string;backup_name:string;table_count:number;row_count:number;created_at:string}>;security:Record<string,boolean>};
const securityLabels: Record<string,string> = {sessionSecret:"مضبوط سیشن خفیہ کلید",supabase:"Supabase محفوظ کنکشن",productionHttps:"Production HTTPS موڈ",cookieProtection:"HttpOnly/SameSite کوکی",roleProtection:"عہدہ اور API اجازت"};
export default function SystemSecurityManager(){
 const [data,setData]=useState<Data|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=()=>fetch("/api/admin/system",{cache:"no-store"}).then(r=>r.json()).then(x=>x.success&&setData(x));
 useEffect(()=>{load()},[]);
 async function snapshot(){setBusy(true);setMessage("");const r=await fetch("/api/admin/system",{method:"POST"});const x=await r.json();setMessage(x.message||"عمل مکمل نہیں ہوسکا۔");setBusy(false);if(x.success)load()}
 return <div className="space-y-7">
  <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-5">{Object.entries(data?.security||{}).map(([k,v])=><div key={k} className={`rounded-2xl border p-5 ${v?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}><div className="text-2xl">{v?"✓":"!"}</div><b className={v?"text-emerald-800":"text-amber-800"}>{securityLabels[k]||k}</b><p className="mt-1 text-xs text-slate-600">{v?"فعال اور درست":"توجہ درکار ہے"}</p></div>)}</section>
  <section className="rounded-2xl bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black text-blue-950">محفوظ بیک اپ</h2><p className="text-sm text-slate-500">Database snapshot محفوظ کریں یا مکمل JSON فائل کمپیوٹر پر اتاریں۔</p></div><div className="flex flex-wrap gap-2"><button disabled={busy} onClick={snapshot} className="rounded-xl bg-blue-900 px-4 py-2 text-white disabled:opacity-50">{busy?"بن رہا ہے…":"ابھی بیک اپ بنائیں"}</button><a href="/api/admin/system?mode=download" className="rounded-xl bg-emerald-700 px-4 py-2 text-white">JSON ڈاؤن لوڈ</a></div></div>{message&&<p className="mt-4 rounded-xl bg-blue-50 p-3 text-blue-900">{message}</p>}<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="bg-slate-100"><th className="p-3 text-right">نام</th><th>ٹیبلز</th><th>ریکارڈز</th><th>تاریخ</th></tr></thead><tbody>{(data?.backups||[]).map(x=><tr key={x.id} className="border-b"><td className="p-3">{x.backup_name}</td><td>{x.table_count}</td><td>{x.row_count}</td><td>{new Date(x.created_at).toLocaleString("ur-PK")}</td></tr>)}</tbody></table></div></section>
  <section className="rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-blue-950">تازہ آڈٹ لاگ</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[750px] text-sm"><thead><tr className="bg-slate-100"><th className="p-3 text-right">صارف</th><th>کارروائی</th><th>ماڈیول</th><th>ریکارڈ</th><th>وقت</th></tr></thead><tbody>{(data?.logs||[]).map(x=><tr key={x.id} className="border-b"><td className="p-3">{x.username}</td><td>{x.action}</td><td>{x.module}</td><td>{x.record_id||"—"}</td><td>{new Date(x.created_at).toLocaleString("ur-PK")}</td></tr>)}</tbody></table></div></section>
 </div>
}
